<?php

namespace App\Controllers\Auth;

use CodeIgniter\HTTP\RedirectResponse;
use CodeIgniter\Shield\Controllers\RegisterController as ShieldRegisterController;

/**
 * Class RegisterController
 *
 * Extends Shield’s built-in registration flow to automatically assign
 * the newly created user to a specific group:
 *   1. The very first user ever registered becomes the “superadmin.”
 *   2. All subsequent users are placed into the configured default group.
 *
 * @package App\Controllers\Auth
 */
class RegisterController extends ShieldRegisterController
{
    /**
     * Handle the user registration form submission.
     *
     * This method wraps Shield’s base registerAction() to add post-registration
     * logic:
     *   1. Count existing users before creating the new one.
     *   2. Delegate to the parent to perform validation, creation, and login.
     *   3. Retrieve the new user record (so we have the ID and entity).
     *   4. Choose a group: “superadmin” if this is the first user,
     *      otherwise the default group from config.
     *   5. Assign (sync) the user into that group.
     *   6. Return the original RedirectResponse so Shield’s redirects
     *      and flash messages still apply.
     *
     * @return RedirectResponse
     *   The redirect response generated by Shield, preserving its status code
     *   and any flash data (e.g., success message).
     *
     * @throws \ReflectionException
     *   Can be thrown by Shield internals if the provider cannot be resolved.
     */
    public function registerAction(): RedirectResponse
    {
        // --------------------------------------------------
        // 1) Count existing users *before* creating the new one
        // --------------------------------------------------
        $users         = $this->getUserProvider();
        $existingCount = $users->countAllResults();

        // --------------------------------------------------
        // 2) Delegate to Shield: validate, create, login, redirect
        //    Shield’s registerAction() returns a RedirectResponse,
        //    but does NOT exit—so we can continue our custom logic.
        // --------------------------------------------------
        $response = parent::registerAction();

        // --------------------------------------------------
        // 3) Retrieve the newly inserted user record
        // --------------------------------------------------
        $newUserId = $users->getInsertID();         // The auto-increment PK
        $user      = $users->findById($newUserId);  // Full user entity

        // --------------------------------------------------
        // 4) Determine which group to assign:
        //    – If no users existed, this is the first → “superadmin”
        //    – Otherwise → configured default group
        // --------------------------------------------------
        /** @var \Config\AuthGroups $authGroupConfig */
        $authGroupConfig = config('AuthGroups');

        $groupName = $existingCount === 0
            ? 'superadmin'
            : $authGroupConfig->defaultGroup;

        // --------------------------------------------------
        // 5) Assign the user to the chosen group.
        //    syncGroups() removes any existing groups and adds the one(s) provided.
        // --------------------------------------------------
        $user->syncGroups($groupName);

        // --------------------------------------------------
        // 6) Return the original RedirectResponse from Shield
        // --------------------------------------------------
        return $response;
    }
}
